language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); include("docs/make.jl")'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
